// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqxzagupsrcufamajbhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxeHphZ3Vwc3JjdWZhbWFqYmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDQ2MzAsImV4cCI6MjA3MDk4MDYzMH0.xc-tqXztHTzSmKDVskPmfl8Swe_ERZ6TjTH8mu7uulM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});